[project]
authors = ["Thomas Wimmer <thomaswimmer@posteo.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "demo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
setuptools = ">=72.1.0,<73"
pip = ">=24.2,<25"
